---
######################
### GeologyManager ###
######################

###Orientation
# 'null'    - No orientation
# 'topo'    - Calculate orientation from a topography array
# 'surface' - Calculate from array of elevation of lower boundary of karst unit (as csv)
orientation_mode     : 'null'
orientation_datafile : ''

###############################
### Fast-Marching Algorithm ###
###############################

#Travel cost parallel to gradient (higher=slower/harder)
#Must be between 0 and 1
cost_out       : 0.999  #default: 0.999
cost_aquifer   : 0.4    #default: 0.4
cost_aquiclude : 0.8    #default: 0.8
cost_faults    : 0.2    #default: 0.2
cost_fractures : 0.2    #default: 0.2
cost_conduits  : 0.1    #default: 0.1
cost_ratio     : 0.5   #ratio of travel cost parallel to gradient / travel cost prependicular to gradient (default 0.25)
#if ratio = 1: same travel cost parallel and perpendicular to gradient
#if ratio < 1: travel cost is lower parallel to gradient (paths will follow steepest gradient), decrease value to increase contrast
#if ratio > 1: travel cost is lower perpendicular to gradient (paths will follow contours), increase value to increase contrast

#############
### Other ###
#############

#Verbosity: how much output to display during run
verbosity : 0    #0: minimal output, 1: some output; 2: more output; 3: maximum output
...