 ##################
### SIM SETTINGS ###
 ##################

---
seed : 0

##############
### Points ###
##############

### Outlets
outlets:
  number     : 3
  data       : [[501, 500], [502, 500], [503, 500], [504, 500]]
  shuffle    : True
  importance : [1]

### Inlets
inlets:
  number     : 3
  data       : [[501, 500], [502, 500], [503, 500], [504, 500]]
  shuffle    : True
  per_outlet : [1,1,1]
  importance : [1,1,1]

### Tracers
tracers:
  number : 1
  data   : ''

####################
### Fracturation ###
####################

fractures:
  data : 'random'
  seed : 12
  settings :
    family_01:
      alpha        : 2
      density      : 0.00001
      orientation  : [340, 20]
      dip          : [80, 90]
      length       : [1000, 2000]
    family_02:
      alpha        : 2
      density      : 0.00001
      orientation  : [340, 20]
      dip          : [0, 10]
      length       : [1000, 2000]

...