 ##################
### SKS SETTINGS ###
 ##################

---
############
### Grid ###
############

grid:
  x0 : 572510
  y0 : 250010
  z0 : 430
  nx : 300
  ny : 300
  nz : 10
  dx : 20
  dy : 20
  dz : 20

############
### Mask ###
############

mask:
  data : 'test/inputs/betteraz_polygon.txt'
  # data : [[3,4,5], [5,6]]

###############
### Geology ###
###############

topography:
  data : 'test/inputs/topography.gslib'

geology:
  data : 'test/inputs/betteraz_2D_z430.gslib'
  # cost : 
  #   1 : 0.5
  #   2 : 0.7

faults:
  data : 'test/inputs/faults.png'
  axis : 'z'
  cost : 
    1 : 0.3
    2 : 0.4


# karst:
#   data : ''

# field:
#   data : ''

###########
### FMM ###
###########

fmm: 
  algorithm : 'Riemann3'
  cost :
    ratio : 0.5

##############
### OTHERS ###
##############

verbosity:
  logging : 0
  agd : 1

debug:
  verbosity: 0
  fmm: False
  
...