 ##################
### SKS SETTINGS ###
 ##################

---
sks:
  seed : 1

############
### Grid ###
############

grid:
  x0 : 572510
  y0 : 250010
  z0 : 430
  nx : 300
  ny : 300
  nz : 10
  dx : 20
  dy : 20
  dz : 20

############
### Mask ###
############

mask:
  data : 'test/inputs/betteraz_polygon.txt'
  # data : [[3,4,5], [5,6]]

###############
### Geology ###
###############

# topography:
#   data : 'test/inputs/topography.gslib'

geology:
  data : 'test/inputs/betteraz_2D_z430.gslib'
  cost : 
    1 : 0.5
    2 : 0.7

faults:
  data : 'test/inputs/faults.png'
  axis : 'z'
  cost : 
    1 : 0.3
    2 : 0.4

# karst:
#   data : ''

# field:
#   data : ''

##############
### Points ###
##############

### Outlets
outlets:
  number     : 6
  data       : 'test/inputs/betteraz_polygon.txt'
  shuffle    : False
  importance : [1,1,1]
  seed : 1
  # z : 'lambda x : x * x'

### Inlets
inlets:
  number     : 30
  data       : 'test/inputs/betteraz_polygon.txt'
  shuffle    : False
  per_outlet : [1,1,1]
  importance : [1,1,1]
  seed : 1
  # z : 'lambda x : x * x'

### Tracers
tracers:
  number : 1
  data   : ''

####################
### Fracturation ###
####################

fractures:
  data : 'random'
  seed : 12
  settings :
    family_01:
      alpha        : 2
      density      : 0.00001
      orientation  : [340, 20]
      dip          : [80, 90]
      length       : [1000, 2000]
    family_02:
      alpha        : 2
      density      : 0.00001
      orientation  : [340, 20]
      dip          : [0, 10]
      length       : [1000, 2000]

###########
### FMM ###
###########

fmm: 
  algorithm : 'Riemann3'
  # cost :
    # ratio : 0.5

##############
### OTHERS ###
##############

verbosity:
  logging : 0
  agd : 1

debug:
  verbosity: 0
  fmm: False
  
...