name: geometry_06b
description: ''
creation_date: 2024/02/28 17:02
pykasso_version: 0.1.2
grid:
  x0: 0
  y0: 0
  z0: 0
  nx: 100
  ny: 1
  nz: 100
  dx: 10
  dy: 10
  dz: 10
core:
  locations:
    root: c:\Users\franc\OneDrive\Desktop\pykasso\pykasso\notebooks\geometry
    project: c:\Users\franc\OneDrive\Desktop\pykasso\pykasso\notebooks\geometry/geometry_06b/
  paths:
    project_dir: geometry_06b/
    inputs_dir: geometry_06b/inputs/
    outputs_dir: geometry_06b/outputs/
  filenames:
    parameters: parameters.yaml
    project: project.yaml
    log: project.log
n_simulations: 2
simulations:
- geometry_06b/outputs/simulation_1/
- geometry_06b/outputs/simulation_2/
