name: pykasso2D_
channels:
  - conda-forge
  - agd-lbr
dependencies:
  - python=3.9
  - numpy
  - pandas
  - jupyter
  - openpyxl
  - mpmath
  - pyyaml
  - matplotlib
  - notebook
  - scipy
  - networkx
  - agd
  - hfm
  - pip
  - pip:
    - mplstereonet