[tool.poetry]
name = "pykasso"
version = "0.1.0"
description = "Python project intended to simulate stochastic karst network"
license = "MIT"
authors = [
    "François Miville <francois@miville.org>",
    "Chloé Fandel",
    "Philippe Renard"
]
maintainers = [
    "François Miville <francois@miville.org>"
]
readme = "README.md"
homepage = ""
repository = "https://github.com/randlab/pyKasso"
documentation = ""
keywords = []
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = [{ include = "misc" }]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.0"
pandas = "^1.5.2"
openpyxl = "^3.0.10"
mpmath = "^1.2.1"
pyyaml = "^6.0"
agd = "^0.1.31"
scipy = "^1.9.3"
karstnet = { git = "https://github.com/karstnet/karstnet.git", branch = "master" }
networkx = "^2.8.8"
mplstereonet = "^0.6.2"

[tool.poetry.group.visualization.dependencies]
matplotlib = "^3.6.2"
pyvista = "^0.37.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.19.4"
jupyter = "^1.0.0"
jupyterlab = "^3.5.2"
ipyvtklink = "^0.2.3"
snakeviz = "^2.1.1"
sphinx = "^6.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"