# pyKasso CORE SETTINGS 
---
core_settings_filename: CORE_SETTINGS.yaml
inputs_directory: test2/inputs/
log_filename: pyKasso.log
outputs_directory: test2/outputs/
project_directory: test2
settings_directory: test2/settings/
sks_settings_filename: SKS_SETTINGS.yaml
...