 ##################
### SKS SETTINGS ###
 ##################

---
############
### Grid ###
############

x0   : 5
y0   : 5
xnum : 100
ynum : 80
dx   : 10
dy   : 10

###############
### Polygon ###
###############

data_has_polygon : True
polygon_data     : 'inputs/valley1/polygon.txt'

####################
### PointManager ###
####################

###Inlets
# 'random'    - full random points
# 'import'    - import points
# 'composite' - add n random points to imported points
inlets_mode    : 'composite'
inlets_data    : 'inputs/valley1/inlets.txt'
inlets_number  : 5
inlets_shuffle : True   #if False: do not shuffle inlet order, if True: shuffle inlet order randomly

###Outlets
# 'random'    - full random points
# 'import'    - import points
# 'composite' - add n random points to imported points
outlets_mode    : 'import'
outlets_data    : 'inputs/valley1/outlets.txt'
outlets_number  : 1
outlets_shuffle : False #if False: do not shuffle inlet order, if True: shuffle inlet order randomly

######################
### GeologyManager ###
######################

###Geology
# 'null'   - No geology
# 'import' - Import geology via GSLIB (old method)
# 'gslib'  - Import geology via GSLIB (new method)
# 'image'  - Import geology via image
# 'csv'    - Import geology via csv
geological_mode     : 'gslib'
geological_datafile : 'inputs/valley1/geo80x100.gslib'

###Topography
#'null'   - No topography
#'csv'    - Import topography from csv file 
topography_mode : 'csv'
topography_datafile : 'inputs/valley1/dem80x100.csv'

###Orientation
#'null'     - No orientation
#'topo'     - Calculate orientation from surface topography
#'contact'  - Calculate from map of elevation of lower boundary of karst unit (as csv)
#'gslib'    - Import from gslib file (in progress)
orientation_mode : 'contact'
orientation_datafile : 'inputs/valley1/contact80x100.csv'

###Faults
# 'null'   - No faults
# 'import' - Import faults
# 'image'  - Import faults via image
faults_mode     : 'null'
faults_datafile : 'inputs/faults.gslib'

###Fractures
# 'null'   - No fractures
# 'import' - Import fractures
# 'image'  - Import fractures via image
# 'random' - Generate random fractures
fractures_mode     : 'random'
fractures_datafile : 'inputs/fractures.gslib'

# If fractures mode is 'generate'
fractures_densities       : [5.83e-5,1.38e-5,2.22e-5,2.5e-5,4.16e-5,6.66e-5,5e-5]
fractures_min_orientation : [      0,     15,     30,    60,    105,    120, 150]
fractures_max_orientation : [     15,     30,     45,   105,    120,    150, 180]

# For fracture size
fractures_alpha      : 2
fractures_min_length : 50
fractures_max_length : 800

###############################
### Fast-Marching Algorithm ###
###############################

#Choose which algorithm to use:
#'Isotropic2': agd-hfm: 2D, equivalent of skfmm
#'Isotropic3': adg-hfm: 3D, equivalent of skfmm
#'Riemann2'  : agd-hfm: 2D, anisotropic, requires an anisotropy vector field (topography or geologic orientation), performs well in high-relief catchments
#'Riemann3'  : agd-hfm: 3D version of anisotropic algorithm
#for more options, see agd-hfm library documentation

algorithm : 'Riemann2'

#Travel cost parallel to gradient (higher=slower/harder)
#Must be between 0 and 1
cost_out       : 0.999  #default: 0.999
cost_aquifer   : 0.3    #default: 0.3
cost_aquiclude : 0.8    #default: 0.8
cost_faults    : 0.2    #default: 0.2
cost_fractures : 0.2    #default: 0.2
cost_conduits  : 0.01    #default: 0.1
cost_ratio     : 0.25   #ratio of travel cost parallel to gradient / travel cost prependicular to gradient

### Formation to consider and FMM code associated
geology_id       : [2,3] # Only for 'import' or 'csv' geological modes
geology_cost     : [cost_aquifer, cost_aquiclude]

###Inlet iteration:
#Length of array indicates number of iterations
#each integer indicates number of inlets to run in that iteration
#sum of integers must equal total number of inlets?
importance_factor : [1,2,3]   #to run a single iteration: [n_inlets]  #to run each inlet separately: [1,1,1,...]

#############
### Other ###
#############

# if 0 = total random
rand_seed : 0

#Verbosity: how much output to display during run 
verbosity : 0    #0: minimal output, 1: some output; 2: maximum output
...
