name: geometry_07
description: ''
creation_date: 2023/10/04 15:44
pykasso_version: 0.1.2
grid:
  x0: 0
  y0: 0
  z0: 0
  nx: 100
  ny: 100
  nz: 50
  dx: 10
  dy: 10
  dz: 10
core:
  locations:
    root: c:\Users\franc\OneDrive\Desktop\pykasso\pykasso\notebooks\geometry
    project: c:\Users\franc\OneDrive\Desktop\pykasso\pykasso\notebooks\geometry/geometry_07/
  paths:
    project_dir: geometry_07/
    inputs_dir: geometry_07/inputs/
    outputs_dir: geometry_07/outputs/
  filenames:
    parameters: parameters.yaml
    project: project.yaml
    log: project.log
n_simulations: 12
simulations:
- geometry_07/outputs/simulation_1/
- geometry_07/outputs/simulation_2/
- geometry_07/outputs/simulation_3/
- geometry_07/outputs/simulation_4/
- geometry_07/outputs/simulation_5/
- geometry_07/outputs/simulation_6/
- geometry_07/outputs/simulation_7/
- geometry_07/outputs/simulation_8/
- geometry_07/outputs/simulation_9/
- geometry_07/outputs/simulation_10/
- geometry_07/outputs/simulation_11/
- geometry_07/outputs/simulation_12/
