# pyKasso CORE SETTINGS 
---
core_settings_filename: CORE_SETTINGS.yaml
inputs_directory: notebooks/test4/inputs/
outputs_directory: notebooks/test4/outputs/
project_directory: notebooks/test4
settings_directory: notebooks/test4/settings/
sim_settings_filename: SIM_SETTINGS.yaml
sks_settings_filename: SKS_SETTINGS.yaml
...