# pyKasso CORE SETTINGS 
---
core_settings_filename: CORE_SETTINGS.yaml
inputs_directory: animation_01/inputs/
log_filename: pyKasso.log
outputs_directory: animation_01/outputs/
project_directory: animation_01
settings_directory: animation_01/settings/
sks_settings_filename: SKS_SETTINGS.yaml
...