 ##################
### SKS SETTINGS ###
 ##################

---
############
### Grid ###
############

x0   : 0
y0   : 0
xnum : 300
ynum : 300
dx   : 10
dy   : 10

###############
### Polygon ###
###############

data_has_polygon : False
polygon_data     : ''

####################
### PointManager ###
####################

###Inlets
# 'random'    - full random points 
# 'import'    - import points
# 'composite' - add n random points to imported points
inlets_mode   : 'random'
inlets_data   : ''
inlets_number : 50

###Outlets
# 'random'    - full random points 
# 'import'    - import points
# 'composite' - add n random points to imported points
outlets_mode   : 'import'
outlets_data   : [[1500, 0]]
outlets_number : 1

######################
### GeologyManager ###
######################

###Geology
# 'null'   - No geology
# 'import' - Import geology
# 'image'  - Import geology via image
geological_mode     : 'null'
geological_datafile : ''

##################################
#NEW
###################################
###Topography
#'null'   - No topography
#'csv'    - Import topography from csv file 
topography_mode : 'null'
topography_datafile : 'inputs/valley1/dem.csv'

###Orientation
#'null'   - No orientation
#'topo'   - Calculate orientation from topography
#'import' - Import from gslib file (in progress)
orientation_mode : 'null'
##################################
#END NEW
###################################

###Faults
# 'null'   - No faults
# 'import' - Import faults
# 'image'  - Import faults via image
faults_mode     : 'null'
faults_datafile : ''

###Fractures
# 'null'   - No fractures
# 'import' - Import fractures
# 'image'  - Import fractures via image
# 'random' - Generate random fractures
fractures_mode     : 'random'
fractures_datafile : ''

# If fractures mode is 'generate'
fractures_densities       : [0.00005,0.0001]
fractures_min_orientation : [    340,    70]
fractures_max_orientation : [     20,   110]

# For fracture size
fractures_alpha : 2                         #changed to fractures_alpha from alpha
fractures_min_length : 100
fractures_max_length : 4000

###############################
### Fast-Marching Algorithm ###
###############################
#Choose which algorithm to use:
#'skfmm'     : scikit fast-marching: 2D, fast, requires minimal inputs, but does not represent high-relief catchments well (original algorithm)
#'Isotropic2': agd-hfm: 2D, equivalent of skfmm
#'Isotropic3': adg-hfm: 3D, equivalent of skfmm
#'Riemann2'  : agd-hfm: 2D, anisotropic, requires an anisotropy vector field (topography or geologic orientation), performs well in high-relief catchments
#'Riemann3'  : agd-hfm: 3D version of anisotropic algorithm
#for more options, see agd-hfm library documentation

algorithm : 'skfmm'

code_out       : 0.1
code_aquifere  : 2
code_aquiclude : 1
code_faults    : 4
code_fractures : 3
code_conduits  : 5

#New for HFM:
#Travel cost parallel to gradient
cost_out       : 0.999   
cost_aquifer   : 0.2
cost_aquiclude : 0.6 
cost_faults    : 0.05
cost_fractures : 0.05
cost_conduits  : 0.1
cost_ratio     : 0.25     #ratio of travel cost parallel to gradient / travel cost prependicular to gradient

### Formation to consider and FMM code associated
geology_id       : [1,2] # Only for 'import' geological mode
geology_velocity : [code_aquifere,code_aquiclude]
geology_cost     : [code_aquifere,code_aquiclude]  #add a parameter for travel cost through a cell


importance_factor : [1,3,5]

#############
### Other ###
#############

rand_seed : 0
...
