name: example_01
description: ''
creation_date: 2023/10/10 16:25
pykasso_version: 0.1.2
grid:
  x0: 0
  y0: 0
  z0: 0
  nx: 300
  ny: 300
  nz: 1
  dx: 10
  dy: 10
  dz: 10
core:
  locations:
    root: c:\Users\franc\OneDrive\Desktop\pykasso\pykasso\notebooks\paper
    project: c:\Users\franc\OneDrive\Desktop\pykasso\pykasso\notebooks\paper/example_01/
  paths:
    project_dir: example_01/
    inputs_dir: example_01/inputs/
    outputs_dir: example_01/outputs/
  filenames:
    parameters: parameters.yaml
    project: project.yaml
    log: project.log
n_simulations: 100
simulations:
- example_01/outputs/simulation_1/
- example_01/outputs/simulation_2/
- example_01/outputs/simulation_3/
- example_01/outputs/simulation_4/
- example_01/outputs/simulation_5/
- example_01/outputs/simulation_6/
- example_01/outputs/simulation_7/
- example_01/outputs/simulation_8/
- example_01/outputs/simulation_9/
- example_01/outputs/simulation_10/
- example_01/outputs/simulation_11/
- example_01/outputs/simulation_12/
- example_01/outputs/simulation_13/
- example_01/outputs/simulation_14/
- example_01/outputs/simulation_15/
- example_01/outputs/simulation_16/
- example_01/outputs/simulation_17/
- example_01/outputs/simulation_18/
- example_01/outputs/simulation_19/
- example_01/outputs/simulation_20/
- example_01/outputs/simulation_21/
- example_01/outputs/simulation_22/
- example_01/outputs/simulation_23/
- example_01/outputs/simulation_24/
- example_01/outputs/simulation_25/
- example_01/outputs/simulation_26/
- example_01/outputs/simulation_27/
- example_01/outputs/simulation_28/
- example_01/outputs/simulation_29/
- example_01/outputs/simulation_30/
- example_01/outputs/simulation_31/
- example_01/outputs/simulation_32/
- example_01/outputs/simulation_33/
- example_01/outputs/simulation_34/
- example_01/outputs/simulation_35/
- example_01/outputs/simulation_36/
- example_01/outputs/simulation_37/
- example_01/outputs/simulation_38/
- example_01/outputs/simulation_39/
- example_01/outputs/simulation_40/
- example_01/outputs/simulation_41/
- example_01/outputs/simulation_42/
- example_01/outputs/simulation_43/
- example_01/outputs/simulation_44/
- example_01/outputs/simulation_45/
- example_01/outputs/simulation_46/
- example_01/outputs/simulation_47/
- example_01/outputs/simulation_48/
- example_01/outputs/simulation_49/
- example_01/outputs/simulation_50/
- example_01/outputs/simulation_51/
- example_01/outputs/simulation_52/
- example_01/outputs/simulation_53/
- example_01/outputs/simulation_54/
- example_01/outputs/simulation_55/
- example_01/outputs/simulation_56/
- example_01/outputs/simulation_57/
- example_01/outputs/simulation_58/
- example_01/outputs/simulation_59/
- example_01/outputs/simulation_60/
- example_01/outputs/simulation_61/
- example_01/outputs/simulation_62/
- example_01/outputs/simulation_63/
- example_01/outputs/simulation_64/
- example_01/outputs/simulation_65/
- example_01/outputs/simulation_66/
- example_01/outputs/simulation_67/
- example_01/outputs/simulation_68/
- example_01/outputs/simulation_69/
- example_01/outputs/simulation_70/
- example_01/outputs/simulation_71/
- example_01/outputs/simulation_72/
- example_01/outputs/simulation_73/
- example_01/outputs/simulation_74/
- example_01/outputs/simulation_75/
- example_01/outputs/simulation_76/
- example_01/outputs/simulation_77/
- example_01/outputs/simulation_78/
- example_01/outputs/simulation_79/
- example_01/outputs/simulation_80/
- example_01/outputs/simulation_81/
- example_01/outputs/simulation_82/
- example_01/outputs/simulation_83/
- example_01/outputs/simulation_84/
- example_01/outputs/simulation_85/
- example_01/outputs/simulation_86/
- example_01/outputs/simulation_87/
- example_01/outputs/simulation_88/
- example_01/outputs/simulation_89/
- example_01/outputs/simulation_90/
- example_01/outputs/simulation_91/
- example_01/outputs/simulation_92/
- example_01/outputs/simulation_93/
- example_01/outputs/simulation_94/
- example_01/outputs/simulation_95/
- example_01/outputs/simulation_96/
- example_01/outputs/simulation_97/
- example_01/outputs/simulation_98/
- example_01/outputs/simulation_99/
- example_01/outputs/simulation_100/
