# pyKasso CORE SETTINGS 
---
core_settings_filename: CORE_SETTINGS.yaml
inputs_directory: geometry_05/inputs/
log_filename: pyKasso.log
outputs_directory: geometry_05/outputs/
project_directory: geometry_05
settings_directory: geometry_05/settings/
sks_settings_filename: SKS_SETTINGS.yaml
...