name: colab_01
description: ''
creation_date: 2024/03/14 21:02
pykasso_version: 0.1.2
grid:
  x0: 0
  y0: 0
  z0: 0
  nx: 100
  ny: 50
  nz: 50
  dx: 10
  dy: 10
  dz: 10
core:
  locations:
    root: c:\Users\franc\OneDrive\Desktop\pykasso\pykasso\notebooks\colab
    project: c:\Users\franc\OneDrive\Desktop\pykasso\pykasso\notebooks\colab/colab_01/
  paths:
    project_dir: colab_01/
    inputs_dir: colab_01/inputs/
    outputs_dir: colab_01/outputs/
  filenames:
    parameters: parameters.yaml
    project: project.yaml
    log: project.log
n_simulations: 2
simulations:
- colab_01/outputs/simulation_1/
- colab_01/outputs/simulation_2/
