name: conceptual_model
description: ''
creation_date: 2024/02/28 18:41
pykasso_version: 0.1.2
grid:
  x0: 0
  y0: 0
  z0: 0
  nx: 100
  ny: 100
  nz: 30
  dx: 10
  dy: 10
  dz: 10
core:
  locations:
    root: c:\Users\franc\OneDrive\Desktop\pykasso\pykasso\notebooks\misc
    project: c:\Users\franc\OneDrive\Desktop\pykasso\pykasso\notebooks\misc/conceptual_model/
  paths:
    project_dir: conceptual_model/
    inputs_dir: conceptual_model/inputs/
    outputs_dir: conceptual_model/outputs/
  filenames:
    parameters: parameters.yaml
    project: project.yaml
    log: project.log
n_simulations: 0
simulations: []
