name: importance_factor
description: ''
creation_date: 2024/02/28 18:43
pykasso_version: 0.1.2
grid:
  x0: 0
  y0: 0
  z0: 0
  nx: 300
  ny: 300
  nz: 1
  dx: 10
  dy: 10
  dz: 10
core:
  locations:
    root: c:\Users\franc\OneDrive\Desktop\pykasso\pykasso\notebooks\misc
    project: c:\Users\franc\OneDrive\Desktop\pykasso\pykasso\notebooks\misc/importance_factor/
  paths:
    project_dir: importance_factor/
    inputs_dir: importance_factor/inputs/
    outputs_dir: importance_factor/outputs/
  filenames:
    parameters: parameters.yaml
    project: project.yaml
    log: project.log
n_simulations: 9
simulations:
- importance_factor/outputs/simulation_1/
- importance_factor/outputs/simulation_2/
- importance_factor/outputs/simulation_3/
- importance_factor/outputs/simulation_4/
- importance_factor/outputs/simulation_5/
- importance_factor/outputs/simulation_6/
- importance_factor/outputs/simulation_7/
- importance_factor/outputs/simulation_8/
- importance_factor/outputs/simulation_9/
