# pyKasso CORE SETTINGS 
---
core_settings_filename: CORE_SETTINGS.yaml
inputs_directory: geometry_04/inputs/
log_filename: pyKasso.log
outputs_directory: geometry_04/outputs/
project_directory: geometry_04
settings_directory: geometry_04/settings/
sks_settings_filename: SKS_SETTINGS.yaml
...